site_name: CKV Cultureel Zelfportret van Tiemen
site_url: https://tiemro.github.io/ckv-czp/
nav:
- Home: 
    - 'index.md'
    - Start: 'start/start.md'
    - Midden: 'midden/index.md'
    - Eind: 'eind/index.md'
- Start: 
    - 'start/start.md'
- Midden:
    - 'midden/index.md'
    - Verwachting: 'midden/verwachting/verwachting.md'
    - Betekenis: 'midden/betekenis/betekenis.md'
    - Vervolg: 'midden/vervolg/vervolg.md'
- Eind:
    - 'eind/index.md'
    - Verwachting: 'eind/verwachting/verwachting.md'
    - Betekenis: 'eind/betekenis/betekenis.md'
    - Vervolg: 'eind/vervolg/vervolg.md'
theme: 
  name: material
  icon:
    repo: fontawesome/brands/github
    annotation: material/plus-circle

  language: nl
  features: 
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.footer
  

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep orange
      accent: deep orange
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep orange
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to light mode



repo_name: tiemro/ckv-czp/
repo_url: https://github.com/tiemro/ckv-czp/
extra:
  generator: false

plugins:
  - search:
      enabled: false
  

markdown_extensions: 
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg